[toolchain]
anchor_version = "0.29.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
seeds = false
skip-local-validator = true
build-without-docker = true

[programs.localnet]
simple_vault = "GGCcGkcUoT1oCbPxkHrxpHDkLDrb9TYN8Hx2ffAEYLaQ"

[programs.devnet]
simple_vault = "GGCcGkcUoT1oCbPxkHrxpHDkLDrb9TYN8Hx2ffAEYLaQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
